minimum_pre_commit_version: "3.5.0"

default_language_version:
  python: python3.11

exclude: |
  ^(
    build/|
    dist/|
    docs/_build/|
    env/|
    htmlcov/|
    test-env/|
    __pycache__/|
    .*\.egg-info/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args:
          - --config=pyproject.toml
          - src/quantium
          - tests
