# codecov.yml
codecov:
  require_ci_to_pass: false

comment:
  layout: "header, diff, files, flags, footer"
  require_changes: false     # still comment even if patch didn’t change coverage
  require_base: false        # allow comment even without a base report
  require_head: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
