name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff-lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install tools
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

  mypy:
    name: MyPy Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install tools
        run: pip install mypy

      # If your project needs local imports to type-check, uncomment:
      # - name: Install project (optional)
      #   run: pip install -e .

      - name: MyPy
        run: mypy src/quantium/
